/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JPAHibernate;

public class LibraryTest {
	/*
	 * @Test public void testSomeLibraryMethod() { LibraryTest classUnderTest = new
	 * LibraryTest(); assertTrue("someLibraryMethod should return 'true'",
	 * classUnderTest.someLibraryMethod()); }
	 */
}
